### ISSUE TITLE
Make the package installable from github

### ISSUE THREAD

**Issue by 10zinten** [OpenPecha/OCR-Pipelines#1]
### `!Important: not to upload to pypi`

- [x] rename `src` to `ocr_pipeline`
- [x] update all the imports
- [x] make sure all the test are passing
- [x] add all dependencies in `setup.py`
- [x] testing
     - [x] create new python environment
     - [x] run `pip install git+https://github.com/OpenPecha/OCR-Pipelines`
     - [x] run it on test data

**Comment by kaldan007** [comment]
all to do completed.

**Comment by 10zinten** [comment]
nice!
