### ISSUE TITLE
[Refactor] Make paths configurable from config instead

### ISSUE THREAD

**Issue by 10zinten** [OpenPecha/OCR-Pipelines#2]
https://github.com/OpenPecha/OCR-Pipelines/blob/c295084c9516e540c1ef8b2e2ef575e887add77c/ocr_pipelines/pipelines.py#L18

- [x] move `img_download_dir` and `ocr_base_dir` to `ImportConfig` class
- [x] refactor `import_pipeline` to use these dirs from config instead

**Comment by kaldan007** [comment]
refactor has been made. please refer the [PR](https://github.com/OpenPecha/OCR-Pipelines/pull/4)

**Comment by 10zinten** [comment]
fix https://github.com/OpenPecha/OCR-Pipelines/pull/4
